export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SIGN_UP_ERROR = 'SIGN_UP_ERROR'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'

export const FETCH_SINGLE_USER_SUCCESS = 'FETCH_SINGLE_USER_SUCCESS'
export const FETCH_SINGLE_USER_ERROR = 'FETCH_SINGLE_USER_ERROR'

export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS'
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR'

export const POST_ARTICLE_SUCCESS = 'POST_ARTICLE_SUCCESS'
export const POST_ARTICLE_ERROR = 'POST_ARTICLE_ERROR'

export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS'
export const DELETE_ARTICLE_ERROR = 'DELETE_ARTICLE_ERROR'

export const FETCH_SINGLE_ARTICLES_SUCCESS = 'FETCH_SINGLE_ARTICLES_SUCCESS'
export const FETCH_SINGLE_ARTICLES_ERROR = 'FETCH_SINGLE_ARTICLES_ERROR'

export const FETCH_WRITERS_SUCCESS = 'FETCH_WRITERS_SUCCESS'
export const FETCH_WRITERS_ERROR = 'FETCH_WRITERS_ERROR'

export const FETCH_SINGLE_WRITERS_SUCCESS = 'FETCH-SINGLE_WRITERS_SUCCESS'
export const FETCH_SINGLE_WRITERS_ERROR = 'FETCH-SINGLE_WRITERS_ERROR'

export const CLEAR_FORM_ERRORS = 'CLEAR_FORM_ERRORS'
export const UNAUTHORIZED = 'UNAUTHORIZED'

