export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SIGN_UP_ERROR = 'SIGN_UP_ERROR'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'

export const FETCH_USER_SUCCESS = 'FETCH-USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH-USERS_ERROR'

export const FETCH_SINGLE_USER_SUCCESS = 'FETCH-SINGLE_USER_SUCCESS'
export const FETCH_SINGLE_USER_ERROR = 'FETCH-SINGLE_USER_ERROR'

export const FETCH_ARTICLES_SUCCESS = 'FETCH-ARTICLES_SUCCESS'
export const FETCH_ARTICLES_ERROR = 'FETCH-ARTICLES_ERROR'

export const FETCH_SINGLE_ARTICLES_SUCCESS = 'FETCH-SINGLE_ARTICLES_SUCCESS'
export const FETCH_SINGLE_ARTICLES_ERROR = 'FETCH-SINGLE_ARTICLES_ERROR'

export const FETCH_WRITERS_SUCCESS = 'FETCH-WRITERS_SUCCESS'
export const FETCH_WRITERS_ERROR = 'FETCH-WRITERS_ERROR'

export const FETCH_SINGLE_WRITERS_SUCCESS = 'FETCH-SINGLE_WRITERS_SUCCESS'
export const FETCH_SINGLE_WRITERS_ERROR = 'FETCH-SINGLE_WRITERS_ERROR'

