
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'

export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'

export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS'
export const FETCH_USER_PROFILE_ERROR = 'FETCH_USER_PROFILE_ERROR'

export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS'
export const UPDATE_USER_PROFILE_ERROR = 'UPDATE_USER_PROFILE_ERROR'

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR'

export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS'
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR'

export const POST_ARTICLE_SUCCESS = 'POST_ARTICLE_SUCCESS'
export const POST_ARTICLE_ERROR = 'POST_ARTICLE_ERROR'

export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS'
export const UNAUTHORIZED = 'UNAUTHORIZED'
export const DELETE_ARTICLE_ERROR = 'DELETE_ARTICLE_ERROR'

export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS'
export const UPDATE_ARTICLE_ERROR = 'UPDATE_ARTICLE_ERROR'

// export const FETCH_SINGLE_ARTICLES_SUCCESS = 'FETCH_SINGLE_ARTICLES_SUCCESS'
// export const FETCH_SINGLE_ARTICLES_ERROR = 'FETCH_SINGLE_ARTICLES_ERROR'

export const FETCH_WRITERS_SUCCESS = 'FETCH_WRITERS_SUCCESS'
export const FETCH_WRITERS_ERROR = 'FETCH_WRITERS_ERROR'

// export const FETCH_SINGLE_WRITERS_SUCCESS = 'FETCH-SINGLE_WRITERS_SUCCESS'
// export const FETCH_SINGLE_WRITERS_ERROR = 'FETCH-SINGLE_WRITERS_ERROR'

export const CLEAR_FORM_ERRORS = 'CLEAR_FORM_ERRORS'

export const LOADING_CONTENT = 'LOADING_CONTENT'
export const LOADING_ARTICLES = 'LOADING_ARTICLES'
export const EDIT_LOADING = 'EDIT_LOADING'
export const USER_LOADING = 'USER_LOADING'
export const WRITERS_LOADING = 'WRITERS_LOADING'
export const USER_PROFILE_LOADING = 'USER_PROFILE_LOADING'
export const USER_EDIT_PROFILE_LOADING = 'USER_EDIT_PROFILE_LOADING'
export const DELETE_ARTICLE_LOADING = 'DELETE_ARTICLE_LOADING'
export const LOADING_PWD_RECOVERY_EMAIL = 'LOADING_PWD_RECOVERY_EMAIL'

export const PASSWORD_RECOVERY_SUCCESS = 'PASSWORD_RECOVERY_SUCCESS'
export const PASSWORD_RECOVERY_ERROR = 'PASSWORD_RECOVERY_ERROR'
export const PASSWORD_RECOVERY_INPUT_ERROR = 'PASSWORD_RECOVERY_INPUT_ERROR'